all:book1 book2 book5

book1:book1.cpp
	g++ -o book1 book1.cpp -lpthread

book2:book2.cpp
	g++ -o book2 book2.cpp -lpthread 

book5:book5.cpp
	g++ -g -o book5 book5.cpp -lpthread

clean:
	rm book1 book2 book5